### ISSUE TITLE
How to write Chart Templates ?

### ISSUE THREAD

**Issue by Dmayset** [Thanksyy/ncNet#1]
I didn't find in the code that the user can select a **chart template** as mentioned in the paper. If I want to specify the chart template, how can I write it?

**Comment by Thanksyy** [comment]
Hi, sorry for the confusion. As introduced in the paper, a chart template is actually equal to the Vega-Zero query template. Therefore, if a user specifies a (bar chart template, with desc order by y-axis), we can initialize the Vega-Zero query template with the following parameters: mark line, sort Y by desc. This functionality has been implemented by the ncNet code (please refer to ncNet.ipynb).
